var 05_instruction_set =
[
    [ "Aget(Analog Get)", "d8/d61/aget.html", null ],
    [ "APut (Analog put)", "da/d48/aput.html", null ],
    [ "Arithmetic Operations", "d6/d72/arithmetic_operations.html", null ],
    [ "Baud Rate", "d4/de0/baud_rate.html", null ],
    [ "CAN Get", "d9/d37/can_get.html", null ],
    [ "CAN Send", "dc/d61/can_send.html", null ],
    [ "Cat (Catenate)", "dc/dd8/cat.html", null ],
    [ "Clear Screen", "db/d30/clear.html", null ],
    [ "CLS the Screen", "d8/d26/cls.html", null ],
    [ "Copy (Copy a file)", "d6/d78/copy.html", null ],
    [ "Create a Register (GPIO)", "d1/dc8/create_reg.html", null ],
    [ "Del (Delete file or directory)", "df/d13/del.html", null ],
    [ "Delay", "df/d8b/delay.html", null ],
    [ "Dir", "dc/df1/dir.html", null ],
    [ "Disable Debug Log", "d9/d00/disable_debug.html", null ],
    [ "Enable Debug Log", "db/dae/enable_debug.html", null ],
    [ "Exit script program execution", "d7/d6b/exit.html", null ],
    [ "For loop", "d4/deb/for.html", null ],
    [ "Format SD disk", "d7/dd9/format.html", null ],
    [ "Function Definition", "df/d14/function.html", null ],
    [ "Generate PWM Signal", "d1/d45/pwm.html", null ],
    [ "Get (Digital In)", "d4/d6f/get.html", null ],
    [ "Goto", "da/d4f/goto.html", null ],
    [ "Help", "d5/d0a/help.html", null ],
    [ "I2C Get", "d1/d78/i2c_get.html", null ],
    [ "I2C Send", "d7/dd7/i2c_send.html", null ],
    [ "IF...ELSE Statements", "dd/de3/if.html", null ],
    [ "InterruptIn", "d9/d27/interruptin.html", null ],
    [ "Label", "de/d34/label.html", null ],
    [ "Mount (mount a SD-Card)", "d1/d00/mount.html", null ],
    [ "Move (move a file from one directory to another)", "d6/d8e/move.html", null ],
    [ "Put (Digital Out)", "d0/d6b/put.html", null ],
    [ "Rem", "df/db8/rem.html", null ],
    [ "Rename (rename a file )", "d6/d2c/rename.html", null ],
    [ "Reset", "de/d29/reset.html", null ],
    [ "Send_script", "df/d7d/send_script.html", null ],
    [ "SERIAL GET", "d9/d87/serial_get.html", null ],
    [ "Print", "d3/d35/print.html", null ],
    [ "SPI Send", "d8/dca/spi_send.html", null ],
    [ "Ticker", "d1/d24/ticker.html", null ],
    [ "Umount (unmount an SD card)", "d5/df6/umount.html", null ],
    [ "Variables", "da/d26/variable.html", null ],
    [ "While loop", "d4/d6e/while.html", null ]
];