var annotated_dup =
[
    [ "_globalGPIO", "d6/d43/union__global_g_p_i_o.html", null ],
    [ "can", "d7/dda/structcan.html", null ],
    [ "DecoderGPIOclass", "d5/d8a/class_decoder_g_p_i_oclass.html", "d5/d8a/class_decoder_g_p_i_oclass" ],
    [ "Flipper", "d1/d91/class_flipper.html", "d1/d91/class_flipper" ],
    [ "fList", "d2/d20/structf_list.html", null ],
    [ "generalPin", "db/d58/uniongeneral_pin.html", null ],
    [ "GlobalGPclass", "d6/df8/class_global_g_pclass.html", "d6/df8/class_global_g_pclass" ],
    [ "GlobalVariables", "d0/d90/class_global_variables.html", "d0/d90/class_global_variables" ],
    [ "Gnode", "db/d65/struct_gnode.html", null ],
    [ "gTObj", "db/d9e/structg_t_obj.html", null ],
    [ "I2C_Communication", "d3/de5/class_i2_c___communication.html", "d3/de5/class_i2_c___communication" ],
    [ "ifInstruction", "d6/dcb/structif_instruction.html", null ],
    [ "intSt", "d6/dd5/structint_st.html", null ],
    [ "lblscript", "d6/d26/structlblscript.html", null ],
    [ "node", "d5/da1/structnode.html", null ],
    [ "pLab", "da/dec/structp_lab.html", null ],
    [ "reg", "df/d4a/classreg.html", "df/d4a/classreg" ],
    [ "RegisterGPIO", "d2/da8/class_register_g_p_i_o.html", "d2/da8/class_register_g_p_i_o" ],
    [ "RingBuffer", "d4/d8f/class_ring_buffer.html", "d4/d8f/class_ring_buffer" ],
    [ "SerialCommunication", "d9/d1f/struct_serial_communication.html", null ],
    [ "SourceCodeLine", "d8/d7e/class_source_code_line.html", "d8/d7e/class_source_code_line" ],
    [ "specialSerial", "d7/db3/classspecial_serial.html", "d7/db3/classspecial_serial" ],
    [ "tb", "d7/d9e/structtb.html", null ],
    [ "token_exchanger", "d4/df8/structtoken__exchanger.html", null ],
    [ "token_for_object", "db/d88/structtoken__for__object.html", null ],
    [ "token_while_object", "de/dbe/structtoken__while__object.html", null ],
    [ "TokenizeToFile", "d9/d57/class_tokenize_to_file.html", "d9/d57/class_tokenize_to_file" ]
];